[package]
name = "wcr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"

[dev-dependencies]
assert_cmd = "2"
predicates = "3.1.3"
rand = "0.8"
pretty_assertions = "1.4.1"
anyhow = "1.0.100"