[package]
name = "findr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
assert_cmd = "2.0.17"
clap = "4.5.48"
distributions = "0.0.2"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
rand = "0.9.2"
regex = "1.12.1"
walkdir = "2.5.0"
