[package]
name = "catr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.48"

[dev-dependencies]
anyhow = "1.0"
pretty_assertions = "1.4"
assert_cmd = "2"
predicates = "3.1.3"
rand = "0.8"